# Generated by Django 5.1.3 on 2024-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
