# Generated by Django 5.1.3 on 2024-11-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0002_alter_userdatabase_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='caste',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
