# Generated by Django 5.1.3 on 2024-11-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0003_userdatabase_age_userdatabase_bio_userdatabase_caste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='cover_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='profile_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
