# Generated by Django 5.1.3 on 2024-11-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0004_userdatabase_cover_image_userdatabase_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
