# Generated by Django 5.1.3 on 2024-11-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0005_alter_userdatabase_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
