# Generated by Django 5.1.3 on 2024-11-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0006_alter_userdatabase_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
