# Generated by Django 5.1.3 on 2024-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0007_alter_userdatabase_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='birth_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='birth_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='birth_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='birth_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='birth_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='birth_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='birth_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='birth_second',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='kundali_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
