# Generated by Django 5.1.3 on 2024-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0008_userdatabase_birth_date_userdatabase_birth_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='kundali_svg',
            field=models.ImageField(blank=True, null=True, upload_to='kundali_svgs/'),
        ),
    ]
