# Generated by Django 5.1.3 on 2024-11-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0009_alter_userdatabase_kundali_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='kundali_svg',
            field=models.FileField(blank=True, null=True, upload_to='kundali_svgs/'),
        ),
    ]
