# Generated by Django 5.1.3 on 2024-12-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0011_alter_userdatabase_kundali_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kundali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('birth_month', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.IntegerField(blank=True, null=True)),
                ('birth_hour', models.IntegerField(blank=True, null=True)),
                ('birth_minute', models.IntegerField(blank=True, null=True)),
                ('birth_second', models.IntegerField(blank=True, null=True)),
                ('birth_location', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_latitude', models.FloatField(blank=True, null=True)),
                ('birth_longitude', models.FloatField(blank=True, null=True)),
                ('kundali_svg', models.FileField(blank=True, max_length=255, null=True, upload_to='kundali_svgs/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('caste', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDatabase',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biwah.user'),
        ),
        migrations.AddField(
            model_name='kundali',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biwah.user'),
        ),
    ]
