# Generated by Django 5.1.3 on 2025-01-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0013_userdatabase_remove_profile_user_delete_kundali_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='complexion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='family_type',
            field=models.CharField(blank=True, choices=[('Nuclear', 'Nuclear'), ('Joint', 'Joint')], max_length=10),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='gotra',
            field=models.CharField(blank=True, choices=[('Bharadwaj', 'Bharadwaj'), ('Kashyap', 'Kashyap'), ('Vashishtha', 'Vashishtha'), ('Vishwamitra', 'Vishwamitra'), ('Gautam', 'Gautam'), ('Jamadagni', 'Jamadagni'), ('Atri', 'Atri'), ('Agastya', 'Agastya'), ('Bhrigu', 'Bhrigu'), ('Angirasa', 'Angirasa'), ('Parashar', 'Parashar'), ('Mudgala', 'Mudgala')], max_length=50),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='habits_drinking',
            field=models.CharField(blank=True, choices=[('Alcoholic', 'Alcoholic'), ('Non-Alcoholic', 'Non-Alcoholic')], max_length=20),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='habits_eating',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='habits_smoking',
            field=models.CharField(blank=True, choices=[('Smoker', 'Smoker'), ('Non-Smoker', 'Non-Smoker')], max_length=20),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Divorce', 'Divorce'), ('Married', 'Married')], max_length=20),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userdatabase',
            name='zodiac',
            field=models.CharField(blank=True, choices=[('Mesha', 'Mesha (Aries)'), ('Vrishabha', 'Vrishabha (Taurus)'), ('Mithuna', 'Mithuna (Gemini)'), ('Karka', 'Karka (Cancer)'), ('Simha', 'Simha (Leo)'), ('Kanya', 'Kanya (Virgo)'), ('Tula', 'Tula (Libra)'), ('Vrischika', 'Vrischika (Scorpio)'), ('Dhanu', 'Dhanu (Sagittarius)'), ('Makara', 'Makara (Capricorn)'), ('Kumbha', 'Kumbha (Aquarius)'), ('Meena', 'Meena (Pisces)')], max_length=20),
        ),
    ]
