# Generated by Django 5.1.3 on 2025-01-31 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0014_userdatabase_address_userdatabase_complexion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_age_min', models.IntegerField(blank=True, null=True)),
                ('p_age_max', models.IntegerField(blank=True, null=True)),
                ('p_religion', models.CharField(blank=True, max_length=50)),
                ('p_caste', models.CharField(blank=True, max_length=50)),
                ('p_gotra', models.CharField(blank=True, choices=[('Bharadwaj', 'Bharadwaj'), ('Kashyap', 'Kashyap'), ('Vashishtha', 'Vashishtha'), ('Vishwamitra', 'Vishwamitra'), ('Gautam', 'Gautam'), ('Jamadagni', 'Jamadagni'), ('Atri', 'Atri'), ('Agastya', 'Agastya'), ('Bhrigu', 'Bhrigu'), ('Angirasa', 'Angirasa'), ('Parashar', 'Parashar'), ('Mudgala', 'Mudgala')], max_length=50)),
                ('p_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('p_zodiac', models.CharField(blank=True, choices=[('Mesha', 'Mesha (Aries)'), ('Vrishabha', 'Vrishabha (Taurus)'), ('Mithuna', 'Mithuna (Gemini)'), ('Karka', 'Karka (Cancer)'), ('Simha', 'Simha (Leo)'), ('Kanya', 'Kanya (Virgo)'), ('Tula', 'Tula (Libra)'), ('Vrischika', 'Vrischika (Scorpio)'), ('Dhanu', 'Dhanu (Sagittarius)'), ('Makara', 'Makara (Capricorn)'), ('Kumbha', 'Kumbha (Aquarius)'), ('Meena', 'Meena (Pisces)')], max_length=20)),
                ('p_habits_drinking', models.CharField(blank=True, choices=[('Alcoholic', 'Alcoholic'), ('Non-Alcoholic', 'Non-Alcoholic')], max_length=20)),
                ('p_habits_eating', models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20)),
                ('p_habits_smoking', models.CharField(blank=True, choices=[('Smoker', 'Smoker'), ('Non-Smoker', 'Non-Smoker')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='biwah.userdatabase')),
            ],
        ),
    ]
