# Generated by Django 5.1.3 on 2025-02-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0015_userpreferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpreferences',
            old_name='p_height',
            new_name='p_height_max',
        ),
        migrations.RenameField(
            model_name='userpreferences',
            old_name='p_weight',
            new_name='p_height_min',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='p_zodiac',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='age_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='caste_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='gotra_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='height_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='p_weight_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='p_weight_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='religion_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='weight_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='caste',
            field=models.CharField(blank=True, choices=[('Bahun', 'Bahun'), ('Chhetri', 'Chhetri'), ('Thakuri', 'Thakuri'), ('Magar', 'Magar'), ('Tharu', 'Tharu'), ('Tamang', 'Tamang'), ('Newar', 'Newar'), ('Rai', 'Rai'), ('Gurung', 'Gurung'), ('Limbu', 'Limbu'), ('Sherpa', 'Sherpa'), ('Yadav', 'Yadav'), ('Kami', 'Kami'), ('Damai', 'Damai'), ('Sarki', 'Sarki')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='education',
            field=models.CharField(blank=True, choices=[('SEE', 'SEE'), ('High School or +2', 'High School or +2'), ('Diploma', 'Diploma'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Buddhist', 'Buddhist'), ('Islam', 'Islam'), ('Christian', 'Christian'), ('Jain', 'Jain'), ('Kiranti', 'Kiranti')], max_length=50),
        ),
    ]
