# Generated by Django 5.1.3 on 2025-03-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biwah', '0016_rename_p_height_userpreferences_p_height_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdatabase',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdatabase',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='p_height_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='p_height_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='p_weight_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='p_weight_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
